defmodule Bonfire.UI.Me.LivePlugs.LoadCurrentUserFromEmbedToken do
  @moduledoc """
  LivePlug that authenticates a LiveView from a signed embed token passed as a
  URL param (`?token=...`).

  Used by iframe embeds where third-party cookies are unavailable. The token is
  generated by `Bonfire.UI.Me.LoginController` after a successful login when
  redirecting back to an allowed external origin (see `IFRAME_ALLOWED_ORIGINS`).

  Add after `LoadCurrentUser` in `on_mount` so it only runs when the session
  cookie didn't already supply a user:

      on_mount {LivePlugs, [
        Bonfire.UI.Me.LivePlugs.LoadCurrentUser,
        Bonfire.UI.Me.LivePlugs.LoadCurrentUserFromEmbedToken
      ]}
  """

  use Bonfire.UI.Common.Web, :live_plug

  @behaviour Bonfire.UI.Common.LivePlugModule

  # Salt namespaces for this token type — NOTE: security comes from SECRET_KEY_BASE, not this value.
  @token_salt "bonfire_embed_token_v1"
  @param_name "bonfire_embed_token"
  @max_age 365 * 24 * 3600

  def on_mount(:default, params, session, socket) do
    with {:ok, socket} <- mount(params, session, socket) do
      {:cont, socket}
    end
  end

  def mount(_, _, %{assigns: %{__context__: %{current_user: %{id: _}}}} = socket),
    do: {:ok, socket}

  def mount(_, _, %{assigns: %{current_user: %{id: _}}} = socket), do: {:ok, socket}

  def mount(%{@param_name => token}, _session, socket) when is_binary(token) do
    case verify_token(token) do
      {:ok, user_id} ->
        user = Bonfire.UI.Me.LivePlugs.LoadCurrentUser.get_current(user_id, nil)
        Bonfire.UI.Me.LivePlugs.LoadCurrentUser.assign_current_user(socket, user)

      :error ->
        {:ok, socket}
    end
  end

  def mount(_, _, socket), do: {:ok, socket}

  @doc "Sign a long-lived embed token for the given user ID."
  def sign(conn_or_endpoint, user_id) do
    Phoenix.Token.sign(conn_or_endpoint, @token_salt, %{user_id: user_id})
  end

  @doc """
  Check whether a conn's query params include a valid `bonfire_embed_token`.

  Used by HTTP-layer plugs (e.g. CSRF, live-socket asset selection) that need to
  know the request will be authenticated at LV mount — without actually loading
  the user into conn assigns (token auth stays LV-only).
  """
  def valid_token?(%Plug.Conn{query_string: qs} = conn) when is_binary(qs) do
    # Hot-path short-circuit: most requests carry no embed token, so avoid
    # parsing the query string at all when the param name isn't present.
    case :binary.match(qs, @param_name) do
      :nomatch ->
        false

      _ ->
        valid_token?(Plug.Conn.fetch_query_params(conn).query_params)
    end
  end

  def valid_token?(%{@param_name => token}) when is_binary(token) do
    match?({:ok, _}, verify_token(token))
  end

  def valid_token?(_), do: false

  defp verify_token(token) do
    endpoint = Bonfire.Common.Config.endpoint_module()

    case Phoenix.Token.verify(endpoint, @token_salt, token, max_age: @max_age) do
      {:ok, %{user_id: user_id}} when is_binary(user_id) -> {:ok, user_id}
      _ -> :error
    end
  end
end
